// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYN3Tl4mI2fgBdlq2ZgiIroseO47t3G8U',
    appId: '1:225911672456:web:42e875adedd96e63e3193d',
    messagingSenderId: '225911672456',
    projectId: 'prak-mobile-24f8a',
    authDomain: 'prak-mobile-24f8a.firebaseapp.com',
    storageBucket: 'prak-mobile-24f8a.firebasestorage.app',
    measurementId: 'G-WPEKX4R5FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj-r2yksjBAmE0tl_7GRh_xbpb0Spdy7g',
    appId: '1:225911672456:android:128876db3359eea8e3193d',
    messagingSenderId: '225911672456',
    projectId: 'prak-mobile-24f8a',
    storageBucket: 'prak-mobile-24f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2y8FbZBdFMsHQaok5kB1crO3gyNGTDR0',
    appId: '1:225911672456:ios:994173eb72f80720e3193d',
    messagingSenderId: '225911672456',
    projectId: 'prak-mobile-24f8a',
    storageBucket: 'prak-mobile-24f8a.firebasestorage.app',
    androidClientId: '225911672456-k0al19ebkr7ckhhvsve10tjgitof8u8c.apps.googleusercontent.com',
    iosClientId: '225911672456-2bovl9gr7fubrk0jcvqlr16t6uoc2oec.apps.googleusercontent.com',
    iosBundleId: 'com.example.myappFirst',
  );
}
